### PR TITLE
add a Back to Top floating button

### PR DESCRIPTION
**Pull request by trosel**
Seen in bottom right

image

### CODE REVIEW

**Comment by vtduncan** [comment]
Hi @trosel, thanks for your contribution and taking a screenshot to make it easy to review!

I’m not quite sure about the purpose of this button. Isn’t going to the top of the page something that browsers handle themselves? When the browser handles this it can do it in a consistent way across all web pages and doesn’t require each page to have a button on it.

I might be missing something here because I do see ‘go to top of page’ links around the web, but I haven’t seen a compelling need for them. I’m balancing this against the desire to keep the page as simple and minimal as possible, so right now I’m leaning away from adding this.

**Comment by trosel** [comment]
>I’m not quite sure about the purpose of this button. 

Doc is super long. If you click a header and go to the bottom, it's annoying to scroll all the way back up.

>Isn’t going to the top of the page something that browsers handle themselves? When the browser handles this it can do it in a consistent way across all web pages and doesn’t require each page to have a button on it.

Is there a button that goes to the top of every page? If so, nobody ever told me this shortcut lol.

**Comment by vtduncan** [comment]
Thanks for elaborating @trosel!

I’m hearing that you feel frustrated having to scroll all the way back to the top of the page after clicking a link in the table of contents. Especially because the guide is one, long web page. It sounds like your need for being able to navigate quickly and easily isn’t being met, so you’d like to add this button.

My perspective is that these existing ways for scrolling to the top of a web page already meet this need:

* Pressing the Home key on desktop browsers.
* Tapping the top status bar on mobile browsers.
* Pressing the back button or swiping to go back on either desktop or mobile.

In fact I think these methods are even better because they work on every web page, don’t take up any space on the web page and don’t require the user to find the particular button on the site they are viewing.

I’m closing this because I’m not seeing a really strong case to add this button. But I appreciate you taking the time to report this and offer a solution regardless. Thank you!

**Comment by trosel** [comment]
> Pressing the Home key on desktop browsers.

Had no idea this key worked this way haha. I think most keyboards don't have this key anymore though (laptops, macs, etc).

> Tapping the top status bar on mobile browsers.

I can't picture how this works

> Pressing the back button or swiping to go back on either desktop or mobile.

Yeah I guess that's obvious. But not intuitive to the user. You'd think back would go back to the previous page.

**Pull request closed without merging**
